const input = document.querySelector('#fruit');
const suggestions = document.querySelector('.suggestions ul');

const fruit = ['Apple', 'Apricot', 'Avocado 🥑', 'Banana', 'Bilberry', 'Blackberry', 'Blackcurrant', 'Blueberry', 'Boysenberry', 'Currant', 'Cherry', 'Coconut', 'Cranberry', 'Cucumber', 'Custard apple', 'Damson', 'Date', 'Dragonfruit', 'Durian', 'Elderberry', 'Feijoa', 'Fig', 'Gooseberry', 'Grape', 'Raisin', 'Grapefruit', 'Guava', 'Honeyberry', 'Huckleberry', 'Jabuticaba', 'Jackfruit', 'Jambul', 'Juniper berry', 'Kiwifruit', 'Kumquat', 'Lemon', 'Lime', 'Loquat', 'Longan', 'Lychee', 'Mango', 'Mangosteen', 'Marionberry', 'Melon', 'Cantaloupe', 'Honeydew', 'Watermelon', 'Miracle fruit', 'Mulberry', 'Nectarine', 'Nance', 'Olive', 'Orange', 'Clementine', 'Mandarine', 'Tangerine', 'Papaya', 'Passionfruit', 'Peach', 'Pear', 'Persimmon', 'Plantain', 'Plum', 'Pineapple', 'Pomegranate', 'Pomelo', 'Quince', 'Raspberry', 'Salmonberry', 'Rambutan', 'Redcurrant', 'Salak', 'Satsuma', 'Soursop', 'Star fruit', 'Strawberry', 'Tamarillo', 'Tamarind', 'Yuzu'];

// meant to take a string input and return an array of fruit names that match or partially match the input
function search(str) {
	let results = [];

	//check if the input string is empty of whitespace
	if(str.trim() === ''){
		return[]; //return an empty array if the search term is empty
	}

//convert input string to lowercase for case-insensitive matching
	const searchTerm = str.toLowerCase();

//filter the fruit array based on whether each fruit contain the search
	const filterFruits = fruit.filter(fruitName => fruitName.toLowerCase().includes(searchTerm));

	return filterFruits;
}

// this function is intended to handle the keyup event on the input field. Would likely call the search function with the input value and update the suggestions accordingly
function searchHandler(e) {
	//get the input value and remove leading/trailing whitespace
	const inputValue = e.target.value.trim();
	 
	//if the input value is empty this will hide the suggestions
	if(inputValue === ''){
		suggestions.style.display = 'none';
		return;
	}

	//call the search function with the input value and get the results
	const searchResults = search(inputValue);

	//extract individual suggestions from searchReslts
	const individualSuggestions = searchResults.map(result => result);

	//show the search results using the showSuggestions function
	showSuggestions(searchResults, inputValue);
}

// supposed to display the suggestions generated by the search function based on the user input
function showSuggestions(results, inputVal) {
//clear the previous suggestions
	suggestions.innerHTML = '';

//Otherwise, populate the suggestions list with the results
	results.forEach(result => {
		const li = document.createElement('li');
		li.textContent = result;
		suggestions.appendChild(li);
	});	
	suggestions.style.display = 'block';
}

// handle the click event on one of the suggested items and update the input field with the selected suggestion
function useSuggestion(e) {
//check if the clicked element is a list item	
	if(e.target.tagName === 'LI'){
		const selectedSuggestion = e.target.textContent;// get the text content of the clicked list item
		input.value = selectedSuggestion;//set the input value to the selected suggestion
		suggestions.style.display = 'none';//hide the suggestions
	}
}

input.addEventListener('keyup', searchHandler);
suggestions.addEventListener('click', useSuggestion);